### ISSUE TITLE
求数据集连接

### ISSUE THREAD

**Issue by MengyaoHe** [youjibiying/GTOT-Tuning#1]
赞

**Comment by youjibiying** [comment]
Dataset can be downloaded from  http://snap.stanford.edu/gnn-pretrain/data/chem_dataset.zip

**Comment by MengyaoHe** [comment]
非常感谢


---- 回复的原邮件 ----
发件人 Jiying ***@***.***>日期 2022年05月29日 12:45收件人 ***@***.***>抄送至 ***@***.***>、State ***@***.***>主题 Re: [youjibiying/GTOT-Tuning] 求数据集连接 (Issue #1)

Dataset can be downloaded from http://snap.stanford.edu/gnn-pretrain/data/chem_dataset.zip
