### ISSUE TITLE
A question about the section 4 of the paper

### ISSUE THREAD

**Issue by wwma** [youjibiying/GTOT-Tuning#2]
thanks for your great work！I have a little question about the section 4——Masked Optimal Transport.
In this section，you said that “Moreover, the defined MWD can recover WD by setting M = 1n×m and it is obvious that Lmw(M, a, b) ≥ Lw(a, b)“.I wonder if there is something wrong with the ”Lmw(M, a, b) ≥ Lw(a, b)“. I think，some elements of the M⊙P will be zero comparing with P，so according to Eq（2）and Eq（3），Lmw（M，a，b）should be smaller.

**Comment by youjibiying** [comment]
Thank you for your interest!  The   $dom ~\mathbf P$  of  MOT is the subset of  OT.  The solution of MOT is not simply masking the solution of OT with $\mathbf M$.
